version: "2"
name: cloud-migration

services:
  app:
    build: .
    image: cloud-migration:app
    platform: linux/amd64
    entrypoint: []
    volumes:
      - .:/app
    environment:
      - AWS_ACCESS_KEY_ID=testing
      - AWS_SECRET_ACCESS_KEY=testing
      - AWS_DEFAULT_REGION=us-east-1
      - MOTO_EC2=http://moto-ec2:5000
      - MOTO_S3=http://moto-s3:5001
      - MOTO_RDS=http://moto-rds:5002
      - PORTAL_DB_PASSWORD=demo
      - REPORTS_DB_PASSWORD=demo
    depends_on:
      - moto-ec2
      - moto-s3
      - moto-rds

  moto-ec2:
    build: docker/moto
    image: cloud-migration:moto
    platform: linux/amd64
    command: ["ec2", "-H", "0.0.0.0", "-p", "5000"]

  moto-s3:
    build: docker/moto
    image: cloud-migration:moto
    platform: linux/amd64
    command: ["s3bucket_path", "-H", "0.0.0.0", "-p", "5001"]

  moto-rds:
    build: docker/moto
    image: cloud-migration:moto
    platform: linux/amd64
    command: ["rds", "-H", "0.0.0.0", "-p", "5002"]

  tf-plan:
    build: .
    image: cloud-migration:app
    platform: linux/amd64
    network_mode: none
    working_dir: /app/terraform
    volumes:
      - .:/app
    environment:
      - AWS_ACCESS_KEY_ID=testing
      - AWS_SECRET_ACCESS_KEY=testing
    entrypoint: ["sh", "/app/scripts/tf_plan_check.sh"]

networks:
  default:
    ipam:
      config:
        - subnet: 172.49.0.0/24
